language: node_js
node_js:
  - 'iojs'

sudo: false

env:
  - PLATFORM=darwin
  - PLATFORM=win32
  - PLATFORM=linux

before_install:
  - npm install -g node-gyp electron electron-prebuilt electron-packager

install:
  - npm install
  - electron-packager ./ SideCar --platform=$PLATFORM --arch=x64 --version=0.28.3
