language: node_js

node_js:
  - 'iojs'

env:
  matrix:
    #- PLATFORM=darwin
    #- PLATFORM=win32
    - PLATFORM=linux

before_install:
  - sudo apt-get install -y libzmq3-dev pkg-config
  - npm install -g node-gyp-install
  - node-gyp-install

install:
  - npm install
