language: node_js
node_js:
  - '0.12'
  - 'iojs'

before_install:
  - sudo apt-get install libzmq3-dev
  - npm install -g node-gyp

install:
  - npm install
  - cd node_modules/zmq && node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
