language: node_js
node_js:
  - 'iojs'

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev
      - pkg-config

env:
  global:
    - ZMQ="git://github.com/zeromq/zeromq4-x.git -b v4.0.5"
    - SODIUM="git://github.com/jedisct1/libsodium.git -b 0.4.5"
  matrix:
    - PLATFORM=darwin
    - PLATFORM=win32
    - PLATFORM=linux

before_install:
  - npm install -g node-gyp electron electron-prebuilt electron-packager

install:
  - npm install
  - electron-packager ./ SideCar --platform=$PLATFORM --arch=x64 --version=0.28.3
