language: node_js

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev
      - pkg-config

env:
  matrix:
    #- PLATFORM=darwin
    #- PLATFORM=win32
    - PLATFORM=linux

before_install:
  - npm install -g node-gyp

install:
  - npm install
  - electron-packager ./ SideCar --platform=$PLATFORM --arch=x64 --version=0.28.3
