language: node_js
node_js:
  - '0.12'
  - 'iojs'

env:
  - npm_config_target=0.28.1 npm_config_arch=x64 npm_config_disturl=https://atom.io/download/atom-shell

before_install:
  - sudo apt-get install libzmq3-dev
  - npm install -g node-gyp

install:
  - HOME=~/.electron-gyp npm install
